### PR TITLE
Vivaldi Warning

### PR DESCRIPTION
**Pull request by BulletMemes**
I'm the only one who has problems with Stylebot not working, so if anyone else with Vivaldi can test Stylebot out, thanks!

### CODE REVIEW

**Comment by LewisTehMinerz** [comment]
you spelt stylish wrong

**Comment by AlexFlipnote** [comment]
Isn't Vivaldi based on Chrome?

**Comment by LewisTehMinerz** [comment]
Yeah

**Comment by BulletMemes** [comment]
Shh i'm tired.

**Comment by BulletMemes** [comment]
Now its working for me..........crap.

**Pull request closed without merging**
